data <-  read_csv('./data/ncbi_sequencemetadata_Apr12.csv')

data_formatted <- data %>%
  
  # format colnames
  rename_with(., ~ tolower(.x)) %>%
  select(-c(submitters, isolation_source, organization, release_date)) %>%
  rename(sequence_length = length,
         sequence_accession = accession,
         sequence_isolate = isolate,
         sequence_completeness = nuc_completeness,
         collection_country = country,
         collection_location = geo_location) %>%
  
  # format date (create date_dec, date_ym date_ymd) %>%
  
  mutate(date_ymd = case_when(complete_date == TRUE ~ suppressWarnings(parsedate::parse_date(collection_date)) %>% 
                                as.Date() )) %>%
  mutate(date_dec = case_when(complete_date == TRUE ~ suppressWarnings(format(round(decimal_date(date_ymd), 2), 
                               nsmall = 2)))) %>%
  mutate(date_ym = case_when(complete_date == TRUE | date_format == 'yyyy-mm'~ 
                               suppressWarnings(parsedate::parse_date(collection_date)) %>% 
                               format(., "%Y-%m"))) %>%
  mutate(date_y = suppressWarnings(format(parsedate::parse_date(collection_date), "%Y"))) %>%
  mutate(date_tipdate = case_when(
    is.na(date_ymd) & is.na(date_ym) ~ date_y,
    is.na(date_ymd) & !is.na(date_ym) ~ date_ym,
    .default = as.character(date_ymd))) %>%
  select(-c(collection_date, date_format, complete_date))
  
  # Format viral genomic region analysed
  
  
  
  # Format host 
  
  
  # Format geolocation
geodata <- read_csv('data/updated_geodata.csv')

grepl("l'aquila|teramo|pescara|^chieti$", location) ~ "italy_abruzzo",
grepl("potenza|matera", location) ~ "italy_basilicata",
grepl("catanzaro|cosenza|reggio calabria|crotone|vibo valentia", location) ~ "italy_calabria",
grepl("napoli|salerno|avellino|benevento|caserta",  location) ~ "italy_campania",
grepl("bologna|ferrara|forlì-cesena|^modena$|^parma$|piacenza|ravenna|reggio emilia|^rimini$",location) ~ "italy_emilia-romagna",
grepl("gorizia|pordenone|trieste|udine|^ud$",  location) ~ "italy_friuli-venezia giulia",
grepl("roma|latina|rieti|viterbo|frosinone",location) ~ "italy_lazio",
grepl("genova|imperia|la spezia|savona",location) ~ "italy_liguria",
grepl("milano|bergamo|brescia|^bs$|^como$|^cr$|^cremona$|lecco|^lodi$|mantova|^mn$|pavia|sondrio|^varese$|lombardy", location) ~ "italy_lombardia",
grepl("ancona|ascoli piceno|fermo|macerata|pesaro e urbino", location) ~ "italy_marche",
grepl("campobasso|isernia", location) ~ "italy_molise",
grepl("torino|alessandria|^asti$|biella|^cuneo$|^novara$|verbano-cusio-ossola|vercelli", location) ~ "italy_piemonte",
grepl("bari|brindisi|foggia|lecce|taranto|barletta-andria-trani|puglia", location) ~ "italy_apulia",
grepl("cagliari|nuoro|oristano|sassari|sud sardegna",  location) ~ "italy_sardegna",
grepl("agrigento|caltanissetta|catania|^enna$|messina|palermo|ragusa|siracusa|trapani",location) ~ "italy_sicily",
grepl("firenze|arezzo|grosseto|livorno|lucca|massa-carrara|^pisa$|pistoia|prato|siena", location) ~ "italy_toscana",
grepl("trento|bolzano", location) ~ "italy_trentino-alto adige",

grepl("perugia|^terni$", location) ~ "italy_umbria",

grepl("^aosta$", location) ~ "italy_valle d'aosta",

grepl("belluno|padova|^pd$|rovigo|treviso|venezia|verona|vicenza|^v[eri]$|^veneto$", location) ~ "italy_veneto",


FormatItaly <- function(x){
  italy <- c(
    "italy_abruzzo_chieti" = '^chieti$',
    "italy_abruzzo_l'aquila" = "l'aquila",
    "italy_abruzzo_pescara" = 'pescara',
    "italy_abruzzo_teramo" = 'teramo',
    "italy_apulia_bari" = '^bari$',
    "italy_apulia_barletta-andria-trani",
    "italy_apulia_brindisi" = 'brindisi',
    "italy_apulia_foggia" = 'foggia',
    "italy_apulia_lecce" = 'lecce',
    "italy_apulia_taranto" = 'taranto',
    "italy_basilicata_matera" = '^matera$',
    "italy_basilicata_potenza" = "potenza",
    "italy_calabria_catanzaro" = "catanzaro",
    "italy_calabria_cosenza" = "cosenza",
    "italy_calabria_crotone" = 'crotone', 
    "italy_calabria_reggio di calabria" = 'reggio di calabria', 
    "italy_calabria_vibo valentia" = 'vibo valentia',
    "italy_campania_avellino" = "avellino",
    "italy_campania_benevento" = "benevento",
    "italy_campania_caserta" = 'caserta',
    "italy_campania_napoli" = 'napoli',
    "italy_campania_salerno" = 'salerno',
    "italy_emilia-romagna_bologna" = 'bologna|bassa bolognese',
    "italy_emilia-romagna_ferrara" = 'ferrara|berra',
    "italy_emilia-romagna_forli' - cesena" = 'forl[ì,i][ -]cesena',
    "italy_emilia-romagna_modena" = 'modena|nonantola|san cesario',
    "italy_emilia-romagna_parma" = '^parma$',
    "italy_emilia-romagna_piacenza" = 'piacenza',
    "italy_emilia-romagna_ravenna" = '^ravenna|massa lombarda',
    "italy_emilia-romagna_reggio nell'emilia" = 'reggio[- ]emilia|san martino in rio',
    "italy_emilia-romagna_rimini" = "rimini$",
    "italy_friuli-venezia giulia_gorizia" = 'gorizia',
    "italy_friuli-venezia giulia_pordenone" = 'pordenone',
    "italy_friuli-venezia giulia_trieste" = 'triest',
    "italy_friuli-venezia giulia_udine" = '^udine', 
    "italy_lazio_frosinone" = 'frosinone',
    "italy_lazio_latina" = '^latina$',
    "italy_lazio_rieti" = '^reiti$',
    "italy_lazio_roma" ='^roma$',
    "italy_lazio_viterbo" = '^viterbo$',
    "italy_liguria_genova" = '^genova$',
    "italy_liguria_imperia" = '^imperia$',
    "italy_liguria_la spezia" = "la spezia",
    "italy_liguria_savona" = 'savona',
    "italy_lombardia_bergamo" = 'bergamo',
    "italy_lombardia_brescia" = 'pozzolengo|brescia|flero',
    "italy_lombardia_como" = '^como$|grandate',
    "italy_lombardia_cremona" = 'cremona',
    "italy_lombardia_lecco" = 'lecco',
    "italy_lombardia_lodi" = 'lodi',
    "italy_lombardia_mantua" = 'mantua',
    "italy_lombardia_milano"= 'milano{0,1}',
    "italy_lombardia_monza and brianza" = 'monza and brianza',
    "italy_lombardia_pavia" = 'pavia',
    "italy_lombardia_sondrio" = 'sondrio',
    "italy_lombardia_varese" = 'varese',
    "italy_marche_ancona" = 'ancona$|senigallia|osimo',
    "italy_marche_ascoli piceno" = 'ascoli piceno',
    "italy_marche_fermo" = 'fermo',
    "italy_marche_macerata"= 'macerata',
    "italy_marche_pesaro e urbino" = 'pesaro(/| e )urbino',
    "italy_molise_campobasso" = 'campobasso',
    "italy_molise_isernia" = 'isernia',
    "italy_piemonte_alessandria" = '(mombello|casale) monferrato|giarole|alessandria',
    "italy_piemonte_asti" = '^asti$',
    "italy_piemonte_biella" = 'biella$',
    "italy_piemonte_cuneo" = '^cuneo$',
    "italy_piemonte_novara" = 'cameri|^novara$',
    "italy_piemonte_torino" = '^torino$',
    "italy_piemonte_verbano-cusio-ossola" = 'verbania|verbano-cusio-ossola',
    "italy_piemonte_vercelli" = 'vercelli',
    "italy_sardegna_cagliari" = 'cagliari',
    "italy_sardegna_carbonia-iglesias" = 'carbonia-iglesias',
    "italy_sardegna_medio campidano" = 'medio campidano',
    "italy_sardegna_nuoro" = 'nuoro',
    #"italy_sardegna_ogliastra",
    #"italy_sardegna_olbia-tempio",
    #"italy_sardegna_oristano",
    # "italy_sardegna_sassari",
    #"italy_sicily_agrigento",
    #"italy_sicily_caltanissetta",
    # "italy_sicily_catania",
    # "italy_sicily_enna",
    #"italy_sicily_messina",
    # "italy_sicily_palermo",
    # "italy_sicily_ragusa",
    #"italy_sicily_syracuse",
    #"italy_sicily_trapani",
    # "italy_toscana_arezzo",
    # "italy_toscana_florence",
    # "italy_toscana_grosseto",
    # "italy_toscana_livorno",
    # "italy_toscana_lucca",
    # "italy_toscana_massa carrara",
    # "italy_toscana_pisa",
    # "italy_toscana_pistoia",
    # "italy_toscana_prato",
    # "italy_toscana_siena",
    # "italy_trentino-alto adige_bolzano",
    # "italy_trentino-alto adige_trento",
    # "italy_umbria_perugia",
    # "italy_umbria_terni",
    # "italy_valle d'aosta_aosta",
    # "italy_veneto_belluno",
    # "italy_veneto_padua",
    #"italy_veneto_rovigo",
    "italy_veneto_treviso" = '^treviso',
    "italy_veneto_venezia" = '^venezia',
    # "italy_veneto_verona",
    # "italy_veneto_vicenza",
    "italy_abruzzo" = 'abruzzo( region){0,1}$',
    "italy_apulia" = 'apulia( region){0,1}$',
    "italy_basilicata" = 'basilicata( region){0,1}$',
    "italy_calabria" = 'calabria( region){0,1}$',
    "italy_campania" = "campania$( region){0,1}",
    "italy_emilia-romagna" = 'emilia[ -]{0,1}romagna( region){0,1}$',
    "italy_friuli-venezia giulia" = 'friuli-venezia giulia( region){0,1}$',
    "italy_lazio" = 'lazio( region){0,1}$|latium( region){0,1}$',
    "italy_liguria" = 'liguria( region){0,1}$',
    "italy_lombardia" = 'lombardy( region){0,1}$|lombardia( region){0,1}$',
    "italy_marche" = "marche( region){0,1}$",
    "italy_molise" = "molise( region){0,1}$",
    "italy_piemonte" = "piemonte$|piedmont( region){0,1}$|pd$",
    "italy_sardegna" = 'sardegna',
    "italy_sicily"= 'sicily( region){0,1}$',
    "italy_toscana" = 'tuscany( region){0,1}|toscana',
    "italy_trentino-alto adige",
    "italy_umbria" = '^(italy: ){0,1}umbria( region){0,1}$',
    "italy_valle d'aosta" = "valle d'aosta( region){0,1}$",
    "italy_veneto" = "veneto( region){0,1}$",
    "italy" = '^italy$' )
  
  for (i in 1:length(italy)){
    if(any(grepl(italy[[i]], x))){
      x <- names(italy)[[i]]
    }
  }
  
  return(x)
}


FormatNetherlands <- function(x){
  italy <- c(
    "italy_abruzzo_chieti" = '^chieti$',
    "italy_abruzzo_l'aquila" = "l'aquila",
    "italy_abruzzo_pescara" = 'pescara',
    "italy_abruzzo_teramo" = 'teramo',
    "italy_apulia_bari" = '^bari$',
    "italy_apulia_barletta-andria-trani",
    "italy_apulia_brindisi" = 'brindisi',
    "italy_apulia_foggia" = 'foggia',
    "italy_apulia_lecce" = 'lecce',
    "italy_apulia_taranto" = 'taranto',
    "italy_basilicata_matera" = '^matera$',
    "italy_basilicata_potenza" = "potenza",
    "italy_calabria_catanzaro" = "catanzaro",
    "italy_calabria_cosenza" = "cosenza",
    "italy_calabria_crotone" = 'crotone', 
    "italy_calabria_reggio di calabria" = 'reggio di calabria', 
    "italy_calabria_vibo valentia" = 'vibo valentia',
    "italy_campania_avellino" = "avellino",
    "italy_campania_benevento" = "benevento",
    "italy_campania_caserta" = 'caserta',
    "italy_campania_napoli" = 'napoli',
    "italy_campania_salerno" = 'salerno',
    "italy_emilia-romagna_bologna" = 'bologna|bassa bolognese',
    "italy_emilia-romagna_ferrara" = 'ferrara|berra',
    "italy_emilia-romagna_forli' - cesena" = 'forl[ì,i][ -]cesena',
    "italy_emilia-romagna_modena" = 'modena|nonantola|san cesario',
    "italy_emilia-romagna_parma" = '^parma$',
    "italy_emilia-romagna_piacenza" = 'piacenza',
    "italy_emilia-romagna_ravenna" = '^ravenna|massa lombarda',
    "italy_emilia-romagna_reggio nell'emilia" = 'reggio[- ]emilia|san martino in rio',
    "italy_emilia-romagna_rimini" = "rimini$",
    "italy_friuli-venezia giulia_gorizia" = 'gorizia',
    "italy_friuli-venezia giulia_pordenone" = 'pordenone',
    "italy_friuli-venezia giulia_trieste" = 'triest',
    "italy_friuli-venezia giulia_udine" = '^udine', 
    "italy_lazio_frosinone" = 'frosinone',
    "italy_lazio_latina" = '^latina$',
    "italy_lazio_rieti" = '^reiti$',
    "italy_lazio_roma" ='^roma$',
    "italy_lazio_viterbo" = '^viterbo$',
    "italy_liguria_genova" = '^genova$',
    "italy_liguria_imperia" = '^imperia$',
    "italy_liguria_la spezia" = "la spezia",
    "italy_liguria_savona" = 'savona',
    "italy_lombardia_bergamo" = 'bergamo',
    "italy_lombardia_brescia" = 'pozzolengo|brescia|flero',
    "italy_lombardia_como" = '^como$|grandate',
    "italy_lombardia_cremona" = 'cremona',
    "italy_lombardia_lecco" = 'lecco',
    "italy_lombardia_lodi" = 'lodi',
    "italy_lombardia_mantua" = 'mantua',
    "italy_lombardia_milano"= 'milano{0,1}',
    "italy_lombardia_monza and brianza" = 'monza and brianza',
    "italy_lombardia_pavia" = 'pavia',
    "italy_lombardia_sondrio" = 'sondrio',
    "italy_lombardia_varese" = 'varese',
    "italy_marche_ancona" = 'ancona$|senigallia|osimo',
    "italy_marche_ascoli piceno" = 'ascoli piceno',
    "italy_marche_fermo" = 'fermo',
    "italy_marche_macerata"= 'macerata',
    "italy_marche_pesaro e urbino" = 'pesaro(/| e )urbino',
    "italy_molise_campobasso" = 'campobasso',
    "italy_molise_isernia" = 'isernia',
    "italy_piemonte_alessandria" = '(mombello|casale) monferrato|giarole|alessandria',
    "italy_piemonte_asti" = '^asti$',
    "italy_piemonte_biella" = 'biella$',
    "italy_piemonte_cuneo" = '^cuneo$',
    "italy_piemonte_novara" = 'cameri|^novara$',
    "italy_piemonte_torino" = '^torino$',
    "italy_piemonte_verbano-cusio-ossola" = 'verbania|verbano-cusio-ossola',
    "italy_piemonte_vercelli" = 'vercelli',
    "italy_sardegna_cagliari" = 'cagliari',
    "italy_sardegna_carbonia-iglesias" = 'carbonia-iglesias',
    "italy_sardegna_medio campidano" = 'medio campidano',
    "italy_sardegna_nuoro" = 'nuoro',
    #"italy_sardegna_ogliastra",
    #"italy_sardegna_olbia-tempio",
    #"italy_sardegna_oristano",
    # "italy_sardegna_sassari",
    #"italy_sicily_agrigento",
    #"italy_sicily_caltanissetta",
    # "italy_sicily_catania",
    # "italy_sicily_enna",
    #"italy_sicily_messina",
    # "italy_sicily_palermo",
    # "italy_sicily_ragusa",
    #"italy_sicily_syracuse",
    #"italy_sicily_trapani",
    # "italy_toscana_arezzo",
    # "italy_toscana_florence",
    # "italy_toscana_grosseto",
    # "italy_toscana_livorno",
    # "italy_toscana_lucca",
    # "italy_toscana_massa carrara",
    # "italy_toscana_pisa",
    # "italy_toscana_pistoia",
    # "italy_toscana_prato",
    # "italy_toscana_siena",
    # "italy_trentino-alto adige_bolzano",
    # "italy_trentino-alto adige_trento",
    # "italy_umbria_perugia",
    # "italy_umbria_terni",
    # "italy_valle d'aosta_aosta",
    # "italy_veneto_belluno",
    # "italy_veneto_padua",
    #"italy_veneto_rovigo",
    "italy_veneto_treviso" = '^treviso',
    "italy_veneto_venezia" = '^venezia',
    # "italy_veneto_verona",
    # "italy_veneto_vicenza",
    "italy_abruzzo" = 'abruzzo( region){0,1}$',
    "italy_apulia" = 'apulia( region){0,1}$',
    "italy_basilicata" = 'basilicata( region){0,1}$',
    "italy_calabria" = 'calabria( region){0,1}$',
    "italy_campania" = "campania$( region){0,1}",
    "italy_emilia-romagna" = 'emilia[ -]{0,1}romagna( region){0,1}$',
    "italy_friuli-venezia giulia" = 'friuli-venezia giulia( region){0,1}$',
    "italy_lazio" = 'lazio( region){0,1}$|latium( region){0,1}$',
    "italy_liguria" = 'liguria( region){0,1}$',
    "italy_lombardia" = 'lombardy( region){0,1}$|lombardia( region){0,1}$',
    "italy_marche" = "marche( region){0,1}$",
    "italy_molise" = "molise( region){0,1}$",
    "italy_piemonte" = "piemonte$|piedmont( region){0,1}$|pd$",
    "italy_sardegna" = 'sardegna',
    "italy_sicily"= 'sicily( region){0,1}$',
    "italy_toscana" = 'tuscany( region){0,1}|toscana',
    "italy_trentino-alto adige",
    "italy_umbria" = '^(italy: ){0,1}umbria( region){0,1}$',
    "italy_valle d'aosta" = "valle d'aosta( region){0,1}$",
    "italy_veneto" = "veneto( region){0,1}$",
    "italy" = '^italy$' )
  
  for (i in 1:length(italy)){
    if(any(grepl(italy[[i]], x))){
      x <- names(italy)[[i]]
    }
  }
  
  return(x)
}

  
  # Make tipnames
  
  
