data <-  read_csv('./data/ncbi_sequencemetadata_Apr12.csv')

data_formatted <- data %>%
  
  # format colnames
  rename_with(., ~ tolower(.x)) %>%
  select(-c(submitters, isolation_source, organization, release_date)) %>%
  rename(sequence_length = length,
         sequence_accession = accession,
         sequence_isolate = isolate,
         sequence_completeness = nuc_completeness,
         collection_country = country,
         collection_location = geo_location) %>%
  
  # format date (create date_dec, date_ym date_ymd) %>%
  
  mutate(date_ymd = case_when(complete_date == TRUE ~ suppressWarnings(parsedate::parse_date(collection_date)) %>% 
                                as.Date() )) %>%
  mutate(date_dec = case_when(complete_date == TRUE ~ suppressWarnings(format(round(decimal_date(date_ymd), 2), 
                               nsmall = 2)))) %>%
  mutate(date_ym = case_when(complete_date == TRUE | date_format == 'yyyy-mm'~ 
                               suppressWarnings(parsedate::parse_date(collection_date)) %>% 
                               format(., "%Y-%m"))) %>%
  mutate(date_y = suppressWarnings(format(parsedate::parse_date(collection_date), "%Y"))) %>%
  mutate(date_tipdate = case_when(
    is.na(date_ymd) & is.na(date_ym) ~ date_y,
    is.na(date_ymd) & !is.na(date_ym) ~ date_ym,
    .default = as.character(date_ymd))) %>%
  select(-c(collection_date, date_format, complete_date))
  
  # Format viral genomic region analysed
  
  
  
  # Format host 
  
  
  # Format geolocation
geodata <- read_csv('data/updated_geodata.csv')

grepl("l'aquila|teramo|pescara|^chieti$", location) ~ "italy_abruzzo",
grepl("potenza|matera", location) ~ "italy_basilicata",
grepl("catanzaro|cosenza|reggio calabria|crotone|vibo valentia", location) ~ "italy_calabria",
grepl("napoli|salerno|avellino|benevento|caserta",  location) ~ "italy_campania",
grepl("bologna|ferrara|forlì-cesena|^modena$|^parma$|piacenza|ravenna|reggio emilia|^rimini$",location) ~ "italy_emilia-romagna",
grepl("gorizia|pordenone|trieste|udine|^ud$",  location) ~ "italy_friuli-venezia giulia",
grepl("roma|latina|rieti|viterbo|frosinone",location) ~ "italy_lazio",
grepl("genova|imperia|la spezia|savona",location) ~ "italy_liguria",
grepl("milano|bergamo|brescia|^bs$|^como$|^cr$|^cremona$|lecco|^lodi$|mantova|^mn$|pavia|sondrio|^varese$|lombardy", location) ~ "italy_lombardia",
grepl("ancona|ascoli piceno|fermo|macerata|pesaro e urbino", location) ~ "italy_marche",
grepl("campobasso|isernia", location) ~ "italy_molise",
grepl("torino|alessandria|^asti$|biella|^cuneo$|^novara$|verbano-cusio-ossola|vercelli", location) ~ "italy_piemonte",
grepl("bari|brindisi|foggia|lecce|taranto|barletta-andria-trani|puglia", location) ~ "italy_apulia",
grepl("cagliari|nuoro|oristano|sassari|sud sardegna",  location) ~ "italy_sardegna",
grepl("agrigento|caltanissetta|catania|^enna$|messina|palermo|ragusa|siracusa|trapani",location) ~ "italy_sicily",
grepl("firenze|arezzo|grosseto|livorno|lucca|massa-carrara|^pisa$|pistoia|prato|siena", location) ~ "italy_toscana",
grepl("trento|bolzano", location) ~ "italy_trentino-alto adige",

grepl("perugia|^terni$", location) ~ "italy_umbria",

grepl("^aosta$", location) ~ "italy_valle d'aosta",

grepl("belluno|padova|^pd$|rovigo|treviso|venezia|verona|vicenza|^v[eri]$|^veneto$", location) ~ "italy_veneto",


FormatItaly <- function(x){
  italy <- c(
    "italy_abruzzo_chieti" = '^chieti$',
    "italy_abruzzo_l'aquila" = "l'aquila",
    "italy_abruzzo_pescara" = 'pescara',
    "italy_abruzzo_teramo" = 'teramo',
    "italy_apulia_bari" = '^bari$',
    "italy_apulia_barletta-andria-trani",
    "italy_apulia_brindisi" = 'brindisi',
    "italy_apulia_foggia" = 'foggia',
    "italy_apulia_lecce" = 'lecce',
    "italy_apulia_taranto" = 'taranto',
    "italy_basilicata_matera" = '^matera$',
    "italy_basilicata_potenza" = "potenza",
    "italy_calabria_catanzaro" = "catanzaro",
    "italy_calabria_cosenza" = "cosenza",
    "italy_calabria_crotone" = 'crotone', 
    "italy_calabria_reggio di calabria" = 'reggio di calabria', 
    "italy_calabria_vibo valentia" = 'vibo valentia',
    "italy_campania_avellino" = "avellino",
    "italy_campania_benevento" = "benevento",
    "italy_campania_caserta" = 'caserta',
    "italy_campania_napoli" = 'napoli',
    "italy_campania_salerno" = 'salerno',
    "italy_emilia-romagna_bologna" = 'bologna|bassa bolognese',
    "italy_emilia-romagna_ferrara" = 'ferrara|berra',
    "italy_emilia-romagna_forli' - cesena" = 'forl[ì,i][ -]cesena',
    "italy_emilia-romagna_modena" = 'modena|nonantola|san cesario',
    "italy_emilia-romagna_parma" = '^parma$',
    "italy_emilia-romagna_piacenza" = 'piacenza',
    "italy_emilia-romagna_ravenna" = '^ravenna|massa lombarda',
    "italy_emilia-romagna_reggio nell'emilia" = 'reggio[- ]emilia|san martino in rio',
    "italy_emilia-romagna_rimini" = "rimini$",
    "italy_friuli-venezia giulia_gorizia" = 'gorizia',
    "italy_friuli-venezia giulia_pordenone" = 'pordenone',
    "italy_friuli-venezia giulia_trieste" = 'triest',
    "italy_friuli-venezia giulia_udine" = '^udine', 
    "italy_lazio_frosinone" = 'frosinone',
    "italy_lazio_latina" = '^latina$',
    "italy_lazio_rieti" = '^reiti$',
    "italy_lazio_roma" ='^roma$',
    "italy_lazio_viterbo" = '^viterbo$',
    "italy_liguria_genova" = '^genova$',
    "italy_liguria_imperia" = '^imperia$',
    "italy_liguria_la spezia" = "la spezia",
    "italy_liguria_savona" = 'savona',
    "italy_lombardia_bergamo" = 'bergamo',
    "italy_lombardia_brescia" = 'pozzolengo|brescia|flero',
    "italy_lombardia_como" = '^como$|grandate',
    "italy_lombardia_cremona" = 'cremona',
    "italy_lombardia_lecco" = 'lecco',
    "italy_lombardia_lodi" = 'lodi',
    "italy_lombardia_mantua" = 'mantua',
    "italy_lombardia_milano"= 'milano{0,1}',
    "italy_lombardia_monza and brianza" = 'monza and brianza',
    "italy_lombardia_pavia" = 'pavia',
    "italy_lombardia_sondrio" = 'sondrio',
    "italy_lombardia_varese" = 'varese',
    "italy_marche_ancona" = 'ancona$|senigallia|osimo',
    "italy_marche_ascoli piceno" = 'ascoli piceno',
    "italy_marche_fermo" = 'fermo',
    "italy_marche_macerata"= 'macerata',
    "italy_marche_pesaro e urbino" = 'pesaro(/| e )urbino',
    "italy_molise_campobasso" = 'campobasso',
    "italy_molise_isernia" = 'isernia',
    "italy_piemonte_alessandria" = '(mombello|casale) monferrato|giarole|alessandria',
    "italy_piemonte_asti" = '^asti$',
    "italy_piemonte_biella" = 'biella$',
    "italy_piemonte_cuneo" = '^cuneo$',
    "italy_piemonte_novara" = 'cameri|^novara$',
    "italy_piemonte_torino" = '^torino$',
    "italy_piemonte_verbano-cusio-ossola" = 'verbania|verbano-cusio-ossola',
    "italy_piemonte_vercelli" = 'vercelli',
    "italy_sardegna_cagliari" = 'cagliari',
    "italy_sardegna_carbonia-iglesias" = 'carbonia-iglesias',
    "italy_sardegna_medio campidano" = 'medio campidano',
    "italy_sardegna_nuoro" = 'nuoro',
    #"italy_sardegna_ogliastra",
    #"italy_sardegna_olbia-tempio",
    #"italy_sardegna_oristano",
    # "italy_sardegna_sassari",
    #"italy_sicily_agrigento",
    #"italy_sicily_caltanissetta",
    # "italy_sicily_catania",
    # "italy_sicily_enna",
    #"italy_sicily_messina",
    # "italy_sicily_palermo",
    # "italy_sicily_ragusa",
    #"italy_sicily_syracuse",
    #"italy_sicily_trapani",
    # "italy_toscana_arezzo",
    # "italy_toscana_florence",
    # "italy_toscana_grosseto",
    # "italy_toscana_livorno",
    # "italy_toscana_lucca",
    # "italy_toscana_massa carrara",
    # "italy_toscana_pisa",
    # "italy_toscana_pistoia",
    # "italy_toscana_prato",
    # "italy_toscana_siena",
    # "italy_trentino-alto adige_bolzano",
    # "italy_trentino-alto adige_trento",
    # "italy_umbria_perugia",
    # "italy_umbria_terni",
    # "italy_valle d'aosta_aosta",
    # "italy_veneto_belluno",
    # "italy_veneto_padua",
    #"italy_veneto_rovigo",
    "italy_veneto_treviso" = '^treviso',
    "italy_veneto_venezia" = '^venezia',
    # "italy_veneto_verona",
    # "italy_veneto_vicenza",
    "italy_abruzzo" = 'abruzzo( region){0,1}$',
    "italy_apulia" = 'apulia( region){0,1}$',
    "italy_basilicata" = 'basilicata( region){0,1}$',
    "italy_calabria" = 'calabria( region){0,1}$',
    "italy_campania" = "campania$( region){0,1}",
    "italy_emilia-romagna" = 'emilia[ -]{0,1}romagna( region){0,1}$',
    "italy_friuli-venezia giulia" = 'friuli-venezia giulia( region){0,1}$',
    "italy_lazio" = 'lazio( region){0,1}$|latium( region){0,1}$',
    "italy_liguria" = 'liguria( region){0,1}$',
    "italy_lombardia" = 'lombardy( region){0,1}$|lombardia( region){0,1}$',
    "italy_marche" = "marche( region){0,1}$",
    "italy_molise" = "molise( region){0,1}$",
    "italy_piemonte" = "piemonte$|piedmont( region){0,1}$|pd$",
    "italy_sardegna" = 'sardegna',
    "italy_sicily"= 'sicily( region){0,1}$',
    "italy_toscana" = 'tuscany( region){0,1}|toscana',
    "italy_trentino-alto adige",
    "italy_umbria" = '^(italy: ){0,1}umbria( region){0,1}$',
    "italy_valle d'aosta" = "valle d'aosta( region){0,1}$",
    "italy_veneto" = "veneto( region){0,1}$",
    "italy" = '^italy$' )
  
  for (i in 1:length(italy)){
    if(any(grepl(italy[[i]], x))){
      x <- names(italy)[[i]]
    }
  }
  
  return(x)
}


FormatNetherlands <- function(x){
  netherlands <- c(
    "netherlands_drenthe_aa en hunze" = "aa en hunze|^(netherlands.*){0,1}eext$",
    "netherlands_drenthe_assen" = "assen",
    "netherlands_drenthe_borger-odoorn" = "borger-odoorn",
    "netherlands_drenthe_coevorden" = "coevorden",
    "netherlands_drenthe_de wolden" = "de wolden|koekange",
    "netherlands_drenthe_emmen" = "emmen",
    "netherlands_drenthe_hoogeveen" = "hoogeveen",
    "netherlands_drenthe_meppel" = "meppel",
    "netherlands_drenthe_midden-drenthe" = "midden-drenthe|middendrexhe",
    "netherlands_drenthe_noordenveld" = "noordenveld",
    "netherlands_drenthe_tynaarlo" = "tynaarlo",
    "netherlands_drenthe_westerveld" = "westerveld",
    "netherlands_flevoland_almere" = "almere",
    "netherlands_flevoland_dronten" = "dronten",
    "netherlands_flevoland_lelystad" = "lelystad",
    "netherlands_flevoland_noordoostpolder" = "noordo{1,2}st(er){0,1}polder",
    "netherlands_flevoland_urk" = "urk",
    "netherlands_flevoland_zeewolde" = "zeewolde",
    "netherlands_fryslân_achtkarspelen" = "achtkarspelen",
    "netherlands_fryslân_ameland" = "ameland",
    "netherlands_fryslân_dantumadeel" = "dantumadeel",
    "netherlands_fryslân_de fryske marren" = "de fryske marren",
    "netherlands_fryslân_harlingen" = "harlingen",
    "netherlands_fryslân_heerenveen" = "heerenveen",
    "netherlands_fryslân_leeuwarden" = "leeuwarden",
    "netherlands_fryslân_noardeast-fryslân" = "noardeast-fryslân",
    "netherlands_fryslân_ooststellingwerf" = "ooststellingwerf",
    "netherlands_fryslân_opsterland" = "opsterland",
    "netherlands_fryslân_schiermonnikoog" = "schiermonnikoog",
    "netherlands_fryslân_smallingerland" = "smallingerland",
    "netherlands_fryslân_súdwest-fryslân" = "súdwest-fryslân",
    "netherlands_fryslân_terschelling" = "terschelling",
    "netherlands_fryslân_tytsjerksteradiel" = "tytsjerksteradiel|eastermar",
    "netherlands_fryslân_vlieland" = "vlieland",
    "netherlands_fryslân_waadhoeke" = "waadhoeke",
    "netherlands_fryslân_weststellingwerf" = "weststellingwerf",
    "netherlands_gelderland_aalten" = "aalten",
    "netherlands_gelderland_apeldoorn" = "apeldoorn",
    "netherlands_gelderland_arnhem" = "arnhem",
    "netherlands_gelderland_barneveld" = "barneveld",
    "netherlands_gelderland_berg en dal" = "berg en dal",
    "netherlands_gelderland_berkelland" = "berkelland",
    "netherlands_gelderland_beuningen" = "beuningen",
    "netherlands_gelderland_bronckhorst" = "bronckhorst",
    "netherlands_gelderland_brummen" = "brummen",
    "netherlands_gelderland_buren" = "buren|^(netherlands.*){0,1}ingen$",
    "netherlands_gelderland_culemborg" = "culemborg",
    "netherlands_gelderland_doesburg" = "doesburg",
    "netherlands_gelderland_doetinchem" = "doetin{0,1}chem",
    "netherlands_gelderland_druten" = "druten",
    "netherlands_gelderland_duiven" = "duiven",
    "netherlands_gelderland_ede" = "ede|bennekom",
    "netherlands_gelderland_elburg" = "elburg",
    "netherlands_gelderland_epe" = "epe",
    "netherlands_gelderland_ermelo" = "ermelo",
    "netherlands_gelderland_harderwijk" = "harderwijk",
    "netherlands_gelderland_hattem" = "hattem",
    "netherlands_gelderland_heerde" = "heerde",
    "netherlands_gelderland_heumen" = "heumen",
    "netherlands_gelderland_kesteren" = "kesteren",
    "netherlands_gelderland_lingewaard" = "lingewaard",
    "netherlands_gelderland_lochem" = "lochem",
    "netherlands_gelderland_maasdriel" = "maasdriel",
    "netherlands_gelderland_montferland" = "montferland",
    "netherlands_gelderland_nijkerk" = "nijkerk",
    "netherlands_gelderland_nijmegen" = "nijmegen",
    "netherlands_gelderland_nunspeet" = "nunspeet",
    "netherlands_gelderland_oldebroek" = "olden{0,1}broek",
    "netherlands_gelderland_oost gelre" = "oost gelre",
    "netherlands_gelderland_oude ijsselstreek" = "oude ijsselstreek",
    "netherlands_gelderland_overbetuwe" = "overbetuwe|andelst",
    "netherlands_gelderland_putten" = "putten",
    "netherlands_gelderland_renkum" = "renkum",
    "netherlands_gelderland_rheden" = "rheden",
    "netherlands_gelderland_rozendaal" = "rozendaal",
    "netherlands_gelderland_scherpenzeel" = "scherpenzeel",
    "netherlands_gelderland_tiel" = "tiel",
    "netherlands_gelderland_voorst" = "voorst",
    "netherlands_gelderland_wageningen" = "wageningen",
    "netherlands_gelderland_west betuwe" = "west betuwe",
    "netherlands_gelderland_west maas en waal" = "west maas en waal",
    "netherlands_gelderland_westervoort" = "west(er){0,1}voort",
    "netherlands_gelderland_wijchen" = "wijchen",
    "netherlands_gelderland_winterswijk" = "winterswijk",
    "netherlands_gelderland_zaltbommel" = "zaltbommel",
    "netherlands_gelderland_zevenaar" = "zevenaar",
    "netherlands_gelderland_zutphen" = "zutphen",
    "netherlands_groningen_eemsdelta" = "eemsdelta|^(netherlands.*){0,1}spijk",
    "netherlands_groningen_groningen" = "groningen",
    "netherlands_groningen_het hogeland" = "het hogeland",
    "netherlands_groningen_midden-groningen" = "midden-groningen",
    "netherlands_groningen_oldambt" = "oldambt",
    "netherlands_groningen_pekela" = "pekela",
    "netherlands_groningen_stadskanaal" = "stadskanaal",
    "netherlands_groningen_veendam" = "veendam",
    "netherlands_groningen_westerkwartier" = "westerkwartier|zuidhorn",
    "netherlands_groningen_westerwolde" = "westerwolde",
    "netherlands_ijsselmeer_ijsselmeer" = "ijsselmeer",
    "netherlands_limburg_beek" = "beek",
    "netherlands_limburg_beekdaelen" = "beekdaelen",
    "netherlands_limburg_beesel" = "beesel",
    "netherlands_limburg_bergen" = "bergen",
    "netherlands_limburg_brunssum" = "brunssum",
    "netherlands_limburg_echt-susteren" = "echt-susteren",
    "netherlands_limburg_eijsden-margraten" = "eijsden-margraten",
    "netherlands_limburg_gennep" = "gennep|ottersum",
    "netherlands_limburg_gulpen-wittem" = "gulpen-wittem",
    "netherlands_limburg_heerlen" = "heerlen",
    "netherlands_limburg_horst aan de maas" = "horst aan de maas",
    "netherlands_limburg_kerkrade" = "kerkrade",
    "netherlands_limburg_landgraaf" = "landgraaf",
    "netherlands_limburg_leudal" = "leudal",
    "netherlands_limburg_maasgouw" = "maasgouw",
    "netherlands_limburg_maastricht" = "maastricht",
    "netherlands_limburg_meerssen" = "meerssen",
    "netherlands_limburg_mook en middelaar" = "mook en middelaar",
    "netherlands_limburg_nederweert" = "nederweert",
    "netherlands_limburg_peel en maas" = "peel en maas",
    "netherlands_limburg_roerdalen" = "roerdalen",
    "netherlands_limburg_roermond" = "roermond",
    "netherlands_limburg_simpelveld" = "simpelveld",
    "netherlands_limburg_sittard-geleen" = "sittard-geleen",
    "netherlands_limburg_stein" = "stein",
    "netherlands_limburg_vaals" = "vaals",
    "netherlands_limburg_valkenburg aan de geul" = "valkenburg aan de geul",
    "netherlands_limburg_venlo" = "venlo",
    "netherlands_limburg_venray" = "venray",
    "netherlands_limburg_voerendaal" = "voerendaal",
    "netherlands_limburg_weert" = "weert",
    "netherlands_noord-brabant_'s-hertogenbosch" = "'s-hertogenbosch|rosmalen",
    "netherlands_noord-brabant_alphen-chaam" = "alphen-chaam",
    "netherlands_noord-brabant_altena" = "altena",
    "netherlands_noord-brabant_asten" = "asten",
    "netherlands_noord-brabant_baarle-nassau" = "baarle-nassau",
    "netherlands_noord-brabant_bergeijk" = "bergeijk",
    "netherlands_noord-brabant_bergen op zoom" = "bergen op zoom",
    "netherlands_noord-brabant_bernheze" = "bernheze",
    "netherlands_noord-brabant_best" = "best",
    "netherlands_noord-brabant_bladel" = "bladel",
    "netherlands_noord-brabant_boekel" = "boekel",
    "netherlands_noord-brabant_boxmeer" = "boxmeer",
    "netherlands_noord-brabant_boxtel" = "boxtel|gelmonde",
    "netherlands_noord-brabant_breda" = "breda",
    "netherlands_noord-brabant_cranendonck" = "cranendonck",
    "netherlands_noord-brabant_cuijk" = "cuijk|st. agatha",
    "netherlands_noord-brabant_deurne" = "deurne",
    "netherlands_noord-brabant_dongen" = "dongen",
    "netherlands_noord-brabant_drimmelen" = "drimmelen",
    "netherlands_noord-brabant_eersel" = "eersel",
    "netherlands_noord-brabant_eindhoven" = "eindhoven",
    "netherlands_noord-brabant_etten-leur" = "etten-leur",
    "netherlands_noord-brabant_geertruidenberg" = "geertruidenberg",
    "netherlands_noord-brabant_geldrop-mierlo" = "geldrop-mierlo",
    "netherlands_noord-brabant_gemert-bakel" = "gemert-bakel",
    "netherlands_noord-brabant_gilze en rijen" = "gilze en rijen",
    "netherlands_noord-brabant_goirle" = "goirle",
    "netherlands_noord-brabant_grave" = "grave",
    "netherlands_noord-brabant_halderberge" = "halderberge",
    "netherlands_noord-brabant_heeze-leende" = "heeze-leende",
    "netherlands_noord-brabant_helmond" = "helmond",
    "netherlands_noord-brabant_heusden" = "heusden|vlijmen",
    "netherlands_noord-brabant_hilvarenbeek" = "hilvarenbeek",
    "netherlands_noord-brabant_laarbeek" = "laarbeek",
    "netherlands_noord-brabant_landerd" = "landerd|^(netherlands.*){0,1}reek$|schaij{0,1}k",
    "netherlands_noord-brabant_loon op zand" = "loon op zand",
    "netherlands_noord-brabant_meierijstad" = "meierijstad",
    "netherlands_noord-brabant_mill en sint hubert" = "mill en sint hubert",
    "netherlands_noord-brabant_moerdijk" = "moerdijk",
    "netherlands_noord-brabant_nuenen c.a." = "nuenen c.a.",
    "netherlands_noord-brabant_oirschot" = "oirschot",
    "netherlands_noord-brabant_oisterwijk" = "oisterwijk",
    "netherlands_noord-brabant_oosterhout" = "oosterhout",
    "netherlands_noord-brabant_oss" = "oss",
    "netherlands_noord-brabant_reusel-de mierden" = "reusel-de mierden",
    "netherlands_noord-brabant_roosendaal" = "roosendaal",
    "netherlands_noord-brabant_rucphen" = "rucphen",
    "netherlands_noord-brabant_sint-michielsgestel" = "sint-michielsgestel",
    "netherlands_noord-brabant_sint anthonis" = "sint anthonis",
    "netherlands_noord-brabant_someren" = "someren|lierop",
    "netherlands_noord-brabant_son en breugel" = "son en breugel",
    "netherlands_noord-brabant_steenbergen" = "steenbergen",
    "netherlands_noord-brabant_tilburg" = "tilburg",
    "netherlands_noord-brabant_uden" = "uden",
    "netherlands_noord-brabant_valkenswaard" = "valkenswaard",
    "netherlands_noord-brabant_veldhoven" = "veldhoven",
    "netherlands_noord-brabant_vught" = "vught",
    "netherlands_noord-brabant_waalre" = "waalre",
    "netherlands_noord-brabant_waalwijk" = "waalwijk",
    "netherlands_noord-brabant_woensdrecht" = "woensdrecht",
    "netherlands_noord-brabant_zundert" = "zundert|wernhout",
    "netherlands_noord-holland_aalsmeer" = "aalsmeer",
    "netherlands_noord-holland_alkmaar" = "alkmaar",
    "netherlands_noord-holland_amstelveen" = "amstelveen",
    "netherlands_noord-holland_amsterdam" = "amsterdam",
    "netherlands_noord-holland_beemster" = "beemster",
    "netherlands_noord-holland_bergen" = "bergen",
    "netherlands_noord-holland_beverwijk" = "beverwijk",
    "netherlands_noord-holland_blaricum" = "blaricum",
    "netherlands_noord-holland_bloemendaal" = "bloemendaal",
    "netherlands_noord-holland_castricum" = "castricum",
    "netherlands_noord-holland_den helder" = "den helder",
    "netherlands_noord-holland_diemen" = "diemen",
    "netherlands_noord-holland_drechterland" = "drechterland",
    "netherlands_noord-holland_edam-volendam" = "edam-volendam",
    "netherlands_noord-holland_enkhuizen" = "enkhuizen",
    "netherlands_noord-holland_gooise meren" = "gooise meren|naarden",
    "netherlands_noord-holland_haarlem" = "haarlem",
    "netherlands_noord-holland_haarlemmermeer" = "haarlemmermeer",
    "netherlands_noord-holland_heemskerk" = "heemskerk",
    "netherlands_noord-holland_heemstede" = "heemstede",
    "netherlands_noord-holland_heerhugowaard" = "heerhugowaard",
    "netherlands_noord-holland_heiloo" = "heiloo",
    "netherlands_noord-holland_hilversum" = "hilversum",
    "netherlands_noord-holland_hollands kroon" = "hollands kroon",
    "netherlands_noord-holland_hoorn" = "hoorn",
    "netherlands_noord-holland_huizen" = "huizen",
    "netherlands_noord-holland_koggenland" = "koggenland",
    "netherlands_noord-holland_landsmeer" = "landsmeer",
    "netherlands_noord-holland_langedijk" = "langedijk",
    "netherlands_noord-holland_laren" = "laren",
    "netherlands_noord-holland_medemblik" = "medemblik",
    "netherlands_noord-holland_oostzaan" = "oostzaan",
    "netherlands_noord-holland_opmeer" = "opmeer",
    "netherlands_noord-holland_ouder-amstel" = "ouder-amstel",
    "netherlands_noord-holland_purmerend" = "purmerend",
    "netherlands_noord-holland_schagen" = "schagen",
    "netherlands_noord-holland_stede broec" = "stede broec",
    "netherlands_noord-holland_texel" = "texel",
    "netherlands_noord-holland_uitgeest" = "uitgeest",
    "netherlands_noord-holland_uithoorn" = "uithoorn",
    "netherlands_noord-holland_velsen" = "velsen",
    "netherlands_noord-holland_waterland" = "waterland",
    "netherlands_noord-holland_weesp" = "weesp",
    "netherlands_noord-holland_wijdemeren" = "wijdemeren",
    "netherlands_noord-holland_wormerland" = "wormerland",
    "netherlands_noord-holland_zaanstad" = "zaanstad",
    "netherlands_noord-holland_zandvoort" = "zandvoort",
    "netherlands_overijssel_almelo" = "almelo",
    "netherlands_overijssel_borne" = "borne",
    "netherlands_overijssel_dalfsen" = "dalfsen",
    "netherlands_overijssel_deventer" = "deventer|devexer",
    "netherlands_overijssel_dinkelland" = "dinkelland",
    "netherlands_overijssel_enschede" = "enschede",
    "netherlands_overijssel_haaksbergen" = "haaksbergen",
    "netherlands_overijssel_hardenberg" = "hardenberg",
    "netherlands_overijssel_hellendoorn" = "hellendoorn",
    "netherlands_overijssel_hengelo" = "hengelo",
    "netherlands_overijssel_hof van twente" = "hof van twente",
    "netherlands_overijssel_kampen" = "kampen",
    "netherlands_overijssel_losser" = "losser|overdinkel",
    "netherlands_overijssel_oldenzaal" = "oldenzaal",
    "netherlands_overijssel_olst-wijhe" = "olst-wijhe",
    "netherlands_overijssel_ommen" = "ommen",
    "netherlands_overijssel_raalte" = "raalte|heino",
    "netherlands_overijssel_rijssen" = "rijssen",
    "netherlands_overijssel_staphorst" = "staphorst",
    "netherlands_overijssel_steenwijkerland" = "steenwijkerland",
    "netherlands_overijssel_tubbergen" = "tubbergen",
    "netherlands_overijssel_twenterand" = "twenterand",
    "netherlands_overijssel_wierden" = "wierden",
    "netherlands_overijssel_zwartewaterland" = "zwartewaterland",
    "netherlands_overijssel_zwolle" = "zwolle",
    "netherlands_utrecht_amersfoort" = "amersfoort",
    "netherlands_utrecht_baarn" = "baarn",
    "netherlands_utrecht_bunnik" = "bunnik",
    "netherlands_utrecht_bunschoten" = "bunschoten",
    "netherlands_utrecht_de bilt" = "de {0,1}bilt|bilthoven",
    "netherlands_utrecht_de ronde venen" = "de {0,1}ronde {0,1}venen",
    "netherlands_utrecht_eemnes" = "eemnes",
    "netherlands_utrecht_houten" = "houten",
    "netherlands_utrecht_ijsselstein" = "ijsselstein",
    "netherlands_utrecht_leusden" = "leusden",
    "netherlands_utrecht_lopik" = "lopik",
    "netherlands_utrecht_montfoort" = "montfoort",
    "netherlands_utrecht_nieuwegein" = "nieuwegein",
    "netherlands_utrecht_oudewater" = "oudewater",
    "netherlands_utrecht_renswoude" = "renswoude",
    "netherlands_utrecht_rhenen" = "rhenen",
    "netherlands_utrecht_soest" = "soest",
    "netherlands_utrecht_stichtse vecht" = "stichtse vecht",
    "netherlands_utrecht_utrecht" = "utrecht|haarzuilens",
    "netherlands_utrecht_utrechtse heuvelrug" = "utrechtse heuvelrug",
    "netherlands_utrecht_veenendaal" = "veenendaal",
    "netherlands_utrecht_vijfheerenlanden" = "vijfheerenlanden",
    "netherlands_utrecht_wijk bij duurstede" = "wijk bij duurstede|langbroek",
    "netherlands_utrecht_woerden" = "woerden",
    "netherlands_utrecht_woudenberg" = "woudenberg",
    "netherlands_utrecht_zeist" = "zeist|bosch en duin",
    "netherlands_zeeland_borsele" = "borsele",
    "netherlands_zeeland_goes" = "goes",
    "netherlands_zeeland_hulst" = "hulst",
    "netherlands_zeeland_kapelle" = "kapelle",
    "netherlands_zeeland_middelburg" = "middelburg",
    "netherlands_zeeland_noord-beveland" = "noord-beveland",
    "netherlands_zeeland_reimerswaal" = "reimerswaal",
    "netherlands_zeeland_schouwen-duiveland" = "schouwen-duiveland",
    "netherlands_zeeland_sluis" = "sluis",
    "netherlands_zeeland_terneuzen" = "terneuzen",
    "netherlands_zeeland_tholen" = "tholen",
    "netherlands_zeeland_veere" = "veere",
    "netherlands_zeeland_vlissingen" = "vlissingen",
    "netherlands_zeeuwse meren_zeeuwse meren" = "zeeuwse meren",
    "netherlands_zuid-holland_'s-gravenhage" = "'s-gravenhage|den haag",
    "netherlands_zuid-holland_alblasserdam" = "alblasserdam",
    "netherlands_zuid-holland_albrandswaard" = "albrandswaard",
    "netherlands_zuid-holland_alphen aan den rijn" = "alphen aan den rijn",
    "netherlands_zuid-holland_barendrecht" = "barendrecht",
    "netherlands_zuid-holland_bodegraven-reeuwijk" = "bodegraven-reeuwijk",
    "netherlands_zuid-holland_brielle" = "brielle",
    "netherlands_zuid-holland_capelle aan den ijssel" = "capelle aan den ijssel",
    "netherlands_zuid-holland_delft" = "delft",
    "netherlands_zuid-holland_dordrecht" = "dordrecht",
    "netherlands_zuid-holland_goeree-overflakkee" = "goeree-overflakkee",
    "netherlands_zuid-holland_gorinchem" = "gorinchem",
    "netherlands_zuid-holland_gouda" = "gouda",
    "netherlands_zuid-holland_hardinxveld-giessendam" = "hardinxveld[- ]{0,1}giessendam",
    "netherlands_zuid-holland_hellevoetsluis" = "hellevoetsluis",
    "netherlands_zuid-holland_hendrik-ido-ambacht" = "hendrik-ido-ambacht",
    "netherlands_zuid-holland_hillegom" = "hillegom",
    "netherlands_zuid-holland_hoeksche waard" = "hoeksche waard",
    "netherlands_zuid-holland_kaag en braassem" = "kaag en braassem",
    "netherlands_zuid-holland_katwijk" = "katwijk",
    "netherlands_zuid-holland_krimpen aan den ijssel" = "krimpen aan den ijssel",
    "netherlands_zuid-holland_krimpenerwaard" = "krimpenerwaard",
    "netherlands_zuid-holland_lansingerland" = "lansingerland",
    "netherlands_zuid-holland_leiden" = "leiden",
    "netherlands_zuid-holland_leiderdorp" = "leiderdorp",
    "netherlands_zuid-holland_leidschendam-voorburg" = "leidschendam-voorburg",
    "netherlands_zuid-holland_lisse" = "lisse",
    "netherlands_zuid-holland_maassluis" = "maassluis",
    "netherlands_zuid-holland_midden-delfland" = "midden-delfland",
    "netherlands_zuid-holland_molenlanden" = "molenlanden",
    "netherlands_zuid-holland_nieuwkoop" = "nieuwkoop",
    "netherlands_zuid-holland_nissewaard" = "nissewaard",
    "netherlands_zuid-holland_noordwijk" = "noordwijk",
    "netherlands_zuid-holland_oegstgeest" = "oegstgeest",
    "netherlands_zuid-holland_papendrecht" = "papendrecht",
    "netherlands_zuid-holland_pijnacker-nootdorp" = "pijnacker-nootdorp",
    "netherlands_zuid-holland_ridderkerk" = "ridderkerk",
    "netherlands_zuid-holland_rijswijk" = "rijswijk",
    "netherlands_zuid-holland_rotterdam" = "rotterdam",
    "netherlands_zuid-holland_schiedam" = "schiedam",
    "netherlands_zuid-holland_sliedrecht" = "sliedrecht",
    "netherlands_zuid-holland_teylingen" = "teylingen",
    "netherlands_zuid-holland_vlaardingen" = "vlaardingen",
    "netherlands_zuid-holland_voorschoten" = "voorschoten",
    "netherlands_zuid-holland_waddinxveen" = "waddinxveen",
    "netherlands_zuid-holland_wassenaar" = "wassenaar",
    "netherlands_zuid-holland_westland" = "westland",
    "netherlands_zuid-holland_westvoorne" = "westvoorne",
    "netherlands_zuid-holland_zoetermeer" = "zoetermeer",
    "netherlands_zuid-holland_zoeterwoude" = "zoeterwoude",
    "netherlands_zuid-holland_zuidplas" = "zuidplas",
    "netherlands_zuid-holland_zwijndrecht" = "zwijndrecht",
    "netherlands_zuid hollandse meren_zuid hollandse meren" = "zuid hollandse meren",
    "netherlands_drenthe" = "^(netherlands.*){0,1}drenthe",
    "netherlands_flevoland" = "^(netherlands.*){0,1}flevoland",
    "netherlands_fryslân" = "^(netherlands.*){0,1}fryslân",
    "netherlands_gelderland" = "^(netherlands.*){0,1}gelderland",
    "netherlands_groningen" = "^(netherlands.*){0,1}groningen",
    "netherlands_ijsselmeer" = "^(netherlands.*){0,1}ijsselmeer",
    "netherlands_limburg" = "^(netherlands.*){0,1}limburg",
    "netherlands_noord-brabant" = "^(netherlands.*){0,1}noord-brabant",
    "netherlands_noord-holland" = "^(netherlands.*){0,1}noord-holland",
    "netherlands_overijssel" = "^(netherlands.*){0,1}overijssel",
    "netherlands_utrecht" = "^(netherlands.*){0,1}utrecht",
    "netherlands_zeeland" = "^(netherlands.*){0,1}zeeland",
    "netherlands_zeeuwse meren" = "^(netherlands.*){0,1}zeeuwse meren",
    "netherlands" = "^netherlands$|grenspad|streekdeliemers")
  
  for (i in 1:length(netherlands)){
    if(any(grepl(netherlands[[i]], x))){
      x <- names(netherlands)[[i]]
    }
  }
  
  return(x)
}

FormatGermany <- function(x){
  germany <- c("germany_baden-württemberg_alb-donau-kreis" = "alb-donau-kreis",
               "germany_baden-württemberg_baden-baden" = "baden-baden",
               "germany_baden-württemberg_biberach" = "biberach",
               "germany_baden-württemberg_böblingen" = "böblingen",
               "germany_baden-württemberg_bodensee" = "bodensee",
               "germany_baden-württemberg_bodenseekreis" = "bodenseekreis",
               "germany_baden-württemberg_breisgau-hochschwarzwald" = "breisgau-hochschwarzwald",
               "germany_baden-württemberg_calw" = "calw",
               "germany_baden-württemberg_emmendingen" = "emmendingen",
               "germany_baden-württemberg_enzkreis" = "enzkreis",
               "germany_baden-württemberg_esslingen" = "esslingen",
               "germany_baden-württemberg_freiburg im breisgau" = "freiburg im breisgau",
               "germany_baden-württemberg_freudenstadt" = "freudenstadt",
               "germany_baden-württemberg_göppingen" = "göppingen",
               "germany_baden-württemberg_heidelberg" = "heidelberg",
               "germany_baden-württemberg_heidenheim" = "heidenheim",
               "germany_baden-württemberg_heilbronn" = "heilbronn",
               "germany_baden-württemberg_heilbronn (stadtkreis)" = "heilbronn (stadtkreis)",
               "germany_baden-württemberg_hohenlohekreis" = "hohenlohekreis",
               "germany_baden-württemberg_karlsruhe" = "karlsruhe",
               "germany_baden-württemberg_karlsruhe (stadtkreis)" = "karlsruhe (stadtkreis)",
               "germany_baden-württemberg_konstanz" = "konstanz",
               "germany_baden-württemberg_lörrach" = "lörrach",
               "germany_baden-württemberg_ludwigsburg" = "ludwigsburg",
               "germany_baden-württemberg_main-tauber-kreis" = "main-tauber-kreis",
               "germany_baden-württemberg_mannheim" = "mannheim",
               "germany_baden-württemberg_neckar-odenwald-kreis" = "neckar-odenwald-kreis",
               "germany_baden-württemberg_ortenaukreis" = "ortenaukreis",
               "germany_baden-württemberg_ostalbkreis" = "ostalbkreis",
               "germany_baden-württemberg_pforzheim" = "pforzheim",
               "germany_baden-württemberg_rastatt" = "rastatt",
               "germany_baden-württemberg_ravensburg" = "ravensburg",
               "germany_baden-württemberg_rems-murr-kreis" = "rems-murr-kreis",
               "germany_baden-württemberg_reutlingen" = "reutlingen",
               "germany_baden-württemberg_rhein-neckar-kreis" = "rhein-neckar-kreis|plankstadt",
               "germany_baden-württemberg_rottweil" = "rottweil",
               "germany_baden-württemberg_schwäbisch hall" = "schwäbisch hall",
               "germany_baden-württemberg_schwarzwald-baar-kreis" = "schwarzwald-baar-kreis",
               "germany_baden-württemberg_sigmaringen" = "sigmaringen",
               "germany_baden-württemberg_stuttgart" = "stuttgart",
               "germany_baden-württemberg_tübingen" = "tübingen",
               "germany_baden-württemberg_tuttlingen" = "tuttlingen",
               "germany_baden-württemberg_ulm" = "ulm",
               "germany_baden-württemberg_waldshut" = "waldshut",
               "germany_baden-württemberg_zollernalbkreis" = "zollernalbkreis",
               "germany_bayern_aichach-friedberg" = "aichach-friedberg",
               "germany_bayern_altötting" = "altötting",
               "germany_bayern_amberg" = "amberg",
               "germany_bayern_amberg-sulzbach" = "amberg-sulzbach",
               "germany_bayern_ansbach" = "ansbach",
               "germany_bayern_ansbach (kreisfreie stadt)" = "ansbach (kreisfreie stadt)",
               "germany_bayern_aschaffenburg" = "aschaffenburg",
               "germany_bayern_aschaffenburg (kreisfreie stadt)" = "aschaffenburg (kreisfreie stadt)",
               "germany_bayern_augsburg" = "augsburg",
               "germany_bayern_augsburg (kreisfreie stadt)" = "augsburg (kreisfreie stadt)",
               "germany_bayern_bad kissingen" = "bad kissingen",
               "germany_bayern_bad tölz-wolfratshausen" = "bad tölz-wolfratshausen",
               "germany_bayern_bamberg" = "bamberg",
               "germany_bayern_bamberg (kreisfreie stadt)" = "bamberg (kreisfreie stadt)",
               "germany_bayern_bayreuth" = "bayreuth",
               "germany_bayern_bayreuth (kreisfreie stadt)" = "bayreuth (kreisfreie stadt)",
               "germany_bayern_berchtesgadener land" = "berchtesgadener land",
               "germany_bayern_cham" = "cham",
               "germany_bayern_coburg" = "coburg",
               "germany_bayern_coburg (kreisfreie stadt)" = "coburg (kreisfreie stadt)",
               "germany_bayern_dachau" = "dachau",
               "germany_bayern_deggendorf" = "deggendorf",
               "germany_bayern_dillingen an der donau" = "dillingen an der donau",
               "germany_bayern_dingolfing-landau" = "dingolfing-landau",
               "germany_bayern_donau-ries" = "donau-ries",
               "germany_bayern_ebersberg" = "ebersberg",
               "germany_bayern_eichstätt" = "eichstätt",
               "germany_bayern_erding" = "erding",
               "germany_bayern_erlangen" = "erlangen",
               "germany_bayern_erlangen-höchstadt" = "erlangen-höchstadt",
               "germany_bayern_forchheim" = "forchheim",
               "germany_bayern_freising" = "freising",
               "germany_bayern_freyung-grafenau" = "freyung-grafenau",
               "germany_bayern_fürstenfeldbruck" = "fürstenfeldbruck",
               "germany_bayern_fürth" = "fürth",
               "germany_bayern_fürth (kreisfreie stadt)" = "fürth (kreisfreie stadt)",
               "germany_bayern_garmisch-partenkirchen" = "garmisch-partenkirchen",
               "germany_bayern_günzburg" = "günzburg",
               "germany_bayern_haßberge" = "haßberge",
               "germany_bayern_hof" = "hof",
               "germany_bayern_hof (kreisfreie stadt)" = "hof (kreisfreie stadt)",
               "germany_bayern_ingolstadt" = "ingolstadt",
               "germany_bayern_kaufbeuren" = "kaufbeuren",
               "germany_bayern_kelheim" = "kelheim",
               "germany_bayern_kempten (allgäu)" = "kempten (allgäu)",
               "germany_bayern_kitzingen" = "kitzingen",
               "germany_bayern_kronach" = "kronach",
               "germany_bayern_kulmbach" = "kulmbach",
               "germany_bayern_landsberg am lech" = "landsberg am lech",
               "germany_bayern_landshut" = "landshut",
               "germany_bayern_landshut (kreisfreie stadt)" = "landshut (kreisfreie stadt)",
               "germany_bayern_lichtenfels" = "lichtenfels",
               "germany_bayern_lindau (bodensee)" = "lindau (bodensee)",
               "germany_bayern_main-spessart" = "main-spessart",
               "germany_bayern_memmingen" = "memmingen",
               "germany_bayern_miesbach" = "miesbach",
               "germany_bayern_miltenberg" = "miltenberg",
               "germany_bayern_mühldorf am inn" = "mühldorf am inn",
               "germany_bayern_münchen" = "münchen",
               "germany_bayern_münchen (kreisfreie stadt)" = "münchen (kreisfreie stadt)",
               "germany_bayern_neu-ulm" = "neu-ulm",
               "germany_bayern_neuburg-schrobenhausen" = "neuburg-schrobenhausen",
               "germany_bayern_neumarkt in der oberpfalz" = "neumarkt in der oberpfalz",
               "germany_bayern_neustadt an der aisch-bad windsh" = "neustadt an der aisch-bad windsh",
               "germany_bayern_neustadt an der waldnaab" = "neustadt an der waldnaab",
               "germany_bayern_nürnberg" = "nürnberg",
               "germany_bayern_nürnberger land" = "nürnberger land",
               "germany_bayern_oberallgäu" = "oberallgäu",
               "germany_bayern_ostallgäu" = "ostallgäu",
               "germany_bayern_passau" = "passau",
               "germany_bayern_passau (kreisfreie stadt)" = "passau (kreisfreie stadt)",
               "germany_bayern_pfaffenhofen an der ilm" = "pfaffenhofen an der ilm",
               "germany_bayern_regen" = "regen",
               "germany_bayern_regensburg" = "regensburg",
               "germany_bayern_regensburg (kreisfreie stadt)" = "regensburg (kreisfreie stadt)",
               "germany_bayern_rhön-grabfeld" = "rhön-grabfeld",
               "germany_bayern_rosenheim" = "rosenheim",
               "germany_bayern_rosenheim (kreisfreie stadt)" = "rosenheim (kreisfreie stadt)",
               "germany_bayern_roth" = "roth",
               "germany_bayern_rottal-inn" = "rottal-inn",
               "germany_bayern_schwabach" = "schwabach",
               "germany_bayern_schwandorf" = "schwandorf",
               "germany_bayern_schweinfurt" = "schweinfurt",
               "germany_bayern_schweinfurt (kreisfreie stadt)" = "schweinfurt (kreisfreie stadt)",
               "germany_bayern_starnberg" = "starnberg",
               "germany_bayern_straubing" = "straubing",
               "germany_bayern_straubing-bogen" = "straubing-bogen",
               "germany_bayern_tirschenreuth" = "tirschenreuth",
               "germany_bayern_traunstein" = "traunstein",
               "germany_bayern_unterallgäu" = "unterallgäu",
               "germany_bayern_weiden in der oberpfalz" = "weiden in der oberpfalz",
               "germany_bayern_weilheim-schongau" = "weilheim-schongau",
               "germany_bayern_weißenburg-gunzenhausen" = "weißenburg-gunzenhausen",
               "germany_bayern_wunsiedel im fichtelgebirge" = "wunsiedel im fichtelgebirge",
               "germany_bayern_würzburg" = "würzburg",
               "germany_bayern_würzburg (kreisfreie stadt)" = "würzburg (kreisfreie stadt)",
               "germany_berlin_berlin" = "berlin",
               "germany_brandenburg_barnim" = "barnim",
               "germany_brandenburg_brandenburg an der havel" = "brandenburg an der havel",
               "germany_brandenburg_cottbus" = "cottbus",
               "germany_brandenburg_dahme-spreewald" = "dahme-spreewald",
               "germany_brandenburg_elbe-elster" = "elbe-elster",
               "germany_brandenburg_frankfurt (oder)" = "frankfurt (oder)",
               "germany_brandenburg_havelland" = "havelland",
               "germany_brandenburg_märkisch-oderland" = "märkisch-oderland",
               "germany_brandenburg_oberhavel" = "oberhavel",
               "germany_brandenburg_oberspreewald-lausitz" = "oberspreewald-lausitz",
               "germany_brandenburg_oder-spree" = "oder-spree",
               "germany_brandenburg_ostprignitz-ruppin" = "ostprignitz-ruppin",
               "germany_brandenburg_potsdam" = "potsdam",
               "germany_brandenburg_potsdam-mittelmark" = "potsdam-mittelmark",
               "germany_brandenburg_prignitz" = "prignitz",
               "germany_brandenburg_spree-neiße" = "spree-neiße",
               "germany_brandenburg_teltow-fläming" = "teltow-fläming",
               "germany_brandenburg_uckermark" = "uckermark",
               "germany_bremen_bremen" = "bremen",
               "germany_bremen_bremerhaven" = "bremerhaven",
               "germany_hamburg_hamburg" = "hamburg",
               "germany_hessen_bergstraße" = "bergstraße",
               "germany_hessen_darmstadt" = "darmstadt",
               "germany_hessen_darmstadt-dieburg" = "darmstadt-dieburg",
               "germany_hessen_frankfurt am main" = "frankfurt am main",
               "germany_hessen_fulda" = "fulda",
               "germany_hessen_gießen" = "gießen",
               "germany_hessen_groß-gerau" = "groß-gerau",
               "germany_hessen_hersfeld-rotenburg" = "hersfeld-rotenburg",
               "germany_hessen_hochtaunuskreis" = "hochtaunuskreis",
               "germany_hessen_kassel" = "kassel",
               "germany_hessen_kassel (kreisfreie stadt)" = "kassel (kreisfreie stadt)",
               "germany_hessen_lahn-dill-kreis" = "lahn-dill-kreis",
               "germany_hessen_limburg-weilburg" = "limburg-weilburg",
               "germany_hessen_main-kinzig-kreis" = "main-kinzig-kreis",
               "germany_hessen_main-taunus-kreis" = "main-taunus-kreis",
               "germany_hessen_marburg-biedenkopf" = "marburg-biedenkopf",
               "germany_hessen_odenwaldkreis" = "odenwaldkreis",
               "germany_hessen_offenbach" = "offenbach",
               "germany_hessen_offenbach am main" = "offenbach am main",
               "germany_hessen_rheingau-taunus-kreis" = "rheingau-taunus-kreis",
               "germany_hessen_schwalm-eder-kreis" = "schwalm-eder-kreis",
               "germany_hessen_vogelsbergkreis" = "vogelsbergkreis",
               "germany_hessen_waldeck-frankenberg" = "waldeck-frankenberg",
               "germany_hessen_werra-meißner-kreis" = "werra-meißner-kreis",
               "germany_hessen_wetteraukreis" = "wetteraukreis",
               "germany_hessen_wiesbaden" = "wiesbaden",
               "germany_mecklenburg-vorpommern_ludwigslust-parchim" = "ludwigslust-parchim",
               "germany_mecklenburg-vorpommern_mecklenburgische seenplatte" = "mecklenburgische seenplatte",
               "germany_mecklenburg-vorpommern_nordwestmecklenburg" = "nordwestmecklenburg",
               "germany_mecklenburg-vorpommern_rostock" = "rostock",
               "germany_mecklenburg-vorpommern_rostock (kreisfreie stadt)" = "rostock (kreisfreie stadt)",
               "germany_mecklenburg-vorpommern_schwerin" = "schwerin",
               "germany_mecklenburg-vorpommern_vorpommern-greifswald" = "vorpommern-greifswald",
               "germany_mecklenburg-vorpommern_vorpommern-rügen" = "vorpommern-rügen",
               "germany_niedersachsen_ammerland" = "ammerland",
               "germany_niedersachsen_aurich" = "aurich",
               "germany_niedersachsen_braunschweig" = "braunschweig",
               "germany_niedersachsen_celle" = "celle",
               "germany_niedersachsen_cloppenburg" = "cloppenburg",
               "germany_niedersachsen_cuxhaven" = "cuxhaven",
               "germany_niedersachsen_delmenhorst" = "delmenhorst",
               "germany_niedersachsen_diepholz" = "diepholz",
               "germany_niedersachsen_emden" = "emden",
               "germany_niedersachsen_emsland" = "emsland",
               "germany_niedersachsen_friesland" = "friesland",
               "germany_niedersachsen_gifhorn" = "gifhorn",
               "germany_niedersachsen_goslar" = "goslar",
               "germany_niedersachsen_göttingen" = "göttingen",
               "germany_niedersachsen_grafschaft bentheim" = "grafschaft bentheim",
               "germany_niedersachsen_hameln-pyrmont" = "hameln-pyrmont",
               "germany_niedersachsen_harburg" = "harburg",
               "germany_niedersachsen_heidekreis" = "heidekreis",
               "germany_niedersachsen_helmstedt" = "helmstedt",
               "germany_niedersachsen_hildesheim" = "hildesheim",
               "germany_niedersachsen_holzminden" = "holzminden",
               "germany_niedersachsen_leer" = "leer",
               "germany_niedersachsen_lüchow-dannenberg" = "lüchow-dannenberg",
               "germany_niedersachsen_lüneburg" = "lüneburg",
               "germany_niedersachsen_nienburg (weser)" = "nienburg (weser)",
               "germany_niedersachsen_northeim" = "northeim",
               "germany_niedersachsen_oldenburg" = "oldenburg",
               "germany_niedersachsen_oldenburg (kreisfreie stadt)" = "oldenburg (kreisfreie stadt)",
               "germany_niedersachsen_osnabrück" = "osnabrück",
               "germany_niedersachsen_osnabrück (kreisfreie stadt)" = "osnabrück (kreisfreie stadt)",
               "germany_niedersachsen_osterholz" = "osterholz",
               "germany_niedersachsen_osterode am harz" = "osterode am harz",
               "germany_niedersachsen_peine" = "peine",
               "germany_niedersachsen_region hannover" = "region hannover",
               "germany_niedersachsen_rotenburg (wümme)" = "rotenburg (wümme)",
               "germany_niedersachsen_salzgitter" = "salzgitter",
               "germany_niedersachsen_schaumburg" = "schaumburg",
               "germany_niedersachsen_stade" = "stade",
               "germany_niedersachsen_uelzen" = "uelzen",
               "germany_niedersachsen_vechta" = "vechta",
               "germany_niedersachsen_verden" = "verden",
               "germany_niedersachsen_wesermarsch" = "wesermarsch",
               "germany_niedersachsen_wilhelmshaven" = "wilhelmshaven",
               "germany_niedersachsen_wittmund" = "wittmund",
               "germany_niedersachsen_wolfenbüttel" = "wolfenbüttel",
               "germany_niedersachsen_wolfsburg" = "wolfsburg",
               "germany_nordrhein-westfalen_bielefeld" = "bielefeld",
               "germany_nordrhein-westfalen_bochum" = "bochum",
               "germany_nordrhein-westfalen_bonn" = "bonn",
               "germany_nordrhein-westfalen_borken" = "borken",
               "germany_nordrhein-westfalen_bottrop" = "bottrop",
               "germany_nordrhein-westfalen_coesfeld" = "coesfeld",
               "germany_nordrhein-westfalen_dortmund" = "dortmund",
               "germany_nordrhein-westfalen_duisburg" = "duisburg",
               "germany_nordrhein-westfalen_düren" = "düren",
               "germany_nordrhein-westfalen_düsseldorf" = "düsseldorf",
               "germany_nordrhein-westfalen_ennepe-ruhr-kreis" = "ennepe-ruhr-kreis",
               "germany_nordrhein-westfalen_essen" = "essen",
               "germany_nordrhein-westfalen_euskirchen" = "euskirchen",
               "germany_nordrhein-westfalen_gelsenkirchen" = "gelsenkirchen",
               "germany_nordrhein-westfalen_gütersloh" = "gütersloh",
               "germany_nordrhein-westfalen_hagen" = "hagen",
               "germany_nordrhein-westfalen_hamm" = "hamm",
               "germany_nordrhein-westfalen_heinsberg" = "heinsberg",
               "germany_nordrhein-westfalen_herford" = "herford",
               "germany_nordrhein-westfalen_herne" = "herne",
               "germany_nordrhein-westfalen_hochsauerlandkreis" = "hochsauerlandkreis",
               "germany_nordrhein-westfalen_höxter" = "höxter",
               "germany_nordrhein-westfalen_kleve" = "kleve",
               "germany_nordrhein-westfalen_köln" = "köln",
               "germany_nordrhein-westfalen_krefeld" = "krefeld",
               "germany_nordrhein-westfalen_leverkusen" = "leverkusen",
               "germany_nordrhein-westfalen_lippe" = "lippe",
               "germany_nordrhein-westfalen_märkischer kreis" = "märkischer kreis",
               "germany_nordrhein-westfalen_mettmann" = "mettmann",
               "germany_nordrhein-westfalen_minden-lübbecke" = "minden-lübbecke",
               "germany_nordrhein-westfalen_mönchengladbach" = "mönchengladbach",
               "germany_nordrhein-westfalen_mülheim an der ruhr" = "mülheim an der ruhr",
               "germany_nordrhein-westfalen_münster" = "münster",
               "germany_nordrhein-westfalen_oberbergischer kreis" = "oberbergischer kreis",
               "germany_nordrhein-westfalen_oberhausen" = "oberhausen",
               "germany_nordrhein-westfalen_olpe" = "olpe",
               "germany_nordrhein-westfalen_paderborn" = "paderborn",
               "germany_nordrhein-westfalen_recklinghausen" = "recklinghausen",
               "germany_nordrhein-westfalen_remscheid" = "remscheid",
               "germany_nordrhein-westfalen_rhein-erft-kreis" = "rhein-erft-kreis",
               "germany_nordrhein-westfalen_rhein-kreis neuss" = "rhein-kreis neuss",
               "germany_nordrhein-westfalen_rhein-sieg-kreis" = "rhein-sieg-kreis",
               "germany_nordrhein-westfalen_rheinisch-bergischer kreis" = "rheinisch-bergischer kreis",
               "germany_nordrhein-westfalen_siegen-wittgenstein" = "siegen-wittgenstein",
               "germany_nordrhein-westfalen_soest" = "soest",
               "germany_nordrhein-westfalen_solingen" = "solingen",
               "germany_nordrhein-westfalen_städteregion aachen" = "städteregion aachen",
               "germany_nordrhein-westfalen_steinfurt" = "steinfurt",
               "germany_nordrhein-westfalen_unna" = "unna",
               "germany_nordrhein-westfalen_viersen" = "viersen",
               "germany_nordrhein-westfalen_warendorf" = "warendorf",
               "germany_nordrhein-westfalen_wesel" = "wesel",
               "germany_nordrhein-westfalen_wuppertal" = "wuppertal",
               "germany_rheinland-pfalz_ahrweiler" = "ahrweiler",
               "germany_rheinland-pfalz_altenkirchen (westerwald)" = "altenkirchen (westerwald)",
               "germany_rheinland-pfalz_alzey-worms" = "alzey-worms",
               "germany_rheinland-pfalz_bad dürkheim" = "bad dürkheim",
               "germany_rheinland-pfalz_bad kreuznach" = "bad kreuznach",
               "germany_rheinland-pfalz_bernkastel-wittlich" = "bernkastel-wittlich",
               "germany_rheinland-pfalz_birkenfeld" = "birkenfeld",
               "germany_rheinland-pfalz_cochem-zell" = "cochem-zell",
               "germany_rheinland-pfalz_donnersbergkreis" = "donnersbergkreis",
               "germany_rheinland-pfalz_eifelkreis bitburg-prüm" = "eifelkreis bitburg-prüm",
               "germany_rheinland-pfalz_frankenthal (pfalz)" = "frankenthal (pfalz)",
               "germany_rheinland-pfalz_germersheim" = "germersheim",
               "germany_rheinland-pfalz_kaiserslautern" = "kaiserslautern",
               "germany_rheinland-pfalz_kaiserslautern (kreisfreie stadt" = "kaiserslautern (kreisfreie stadt)",
               "germany_rheinland-pfalz_koblenz" = "koblenz",
               "germany_rheinland-pfalz_kusel" = "kusel",
               "germany_rheinland-pfalz_landau in der pfalz" = "landau in der pfalz",
               "germany_rheinland-pfalz_ludwigshafen am rhein" = "ludwigshafen am rhein",
               "germany_rheinland-pfalz_mainz" = "mainz",
               "germany_rheinland-pfalz_mainz-bingen" = "mainz-bingen",
               "germany_rheinland-pfalz_mayen-koblenz" = "mayen-koblenz",
               "germany_rheinland-pfalz_neustadt an der weinstraße" = "neustadt an der weinstraße",
               "germany_rheinland-pfalz_neuwied" = "neuwied",
               "germany_rheinland-pfalz_pirmasens" = "pirmasens",
               "germany_rheinland-pfalz_rhein-hunsrück-kreis" = "rhein-hunsrück-kreis",
               "germany_rheinland-pfalz_rhein-lahn-kreis" = "rhein-lahn-kreis",
               "germany_rheinland-pfalz_rhein-pfalz-kreis" = "rhein-pfalz-kreis",
               "germany_rheinland-pfalz_speyer" = "speyer",
               "germany_rheinland-pfalz_südliche weinstraße" = "südliche weinstraße",
               "germany_rheinland-pfalz_südwestpfalz" = "südwestpfalz",
               "germany_rheinland-pfalz_trier" = "trier",
               "germany_rheinland-pfalz_trier-saarburg" = "trier-saarburg",
               "germany_rheinland-pfalz_vulkaneifel" = "vulkaneifel",
               "germany_rheinland-pfalz_westerwaldkreis" = "westerwaldkreis",
               "germany_rheinland-pfalz_worms" = "worms",
               "germany_rheinland-pfalz_zweibrücken" = "zweibrücken",
               "germany_saarland_merzig-wadern" = "merzig-wadern",
               "germany_saarland_neunkirchen" = "neunkirchen",
               "germany_saarland_regionalverband saarbrücken" = "regionalverband saarbrücken",
               "germany_saarland_saarlouis" = "saarlouis",
               "germany_saarland_saarpfalz-kreis" = "saarpfalz-kreis",
               "germany_saarland_st. wendel" = "st. wendel",
               "germany_sachsen_bautzen" = "bautzen",
               "germany_sachsen_chemnitz" = "chemnitz",
               "germany_sachsen_dresden" = "dresden",
               "germany_sachsen_erzgebirgskreis" = "erzgebirgskreis",
               "germany_sachsen_görlitz" = "görlitz",
               "germany_sachsen_leipzig" = "leipzig",
               "germany_sachsen_leipzig (kreisfreie stadt)" = "leipzig (kreisfreie stadt)",
               "germany_sachsen_meißen" = "meißen",
               "germany_sachsen_mittelsachsen" = "mittelsachsen",
               "germany_sachsen_nordsachsen" = "nordsachsen",
               "germany_sachsen_sächsische schweiz-osterzgebirge" = "sächsische schweiz-osterzgebirge",
               "germany_sachsen_vogtlandkreis" = "vogtlandkreis",
               "germany_sachsen_zwickau" = "zwickau",
               "germany_sachsen-anhalt_altmarkkreis salzwedel" = "altmarkkreis salzwedel",
               "germany_sachsen-anhalt_anhalt-bitterfeld" = "anhalt-bitterfeld",
               "germany_sachsen-anhalt_börde" = "börde",
               "germany_sachsen-anhalt_burgenlandkreis" = "burgenlandkreis",
               "germany_sachsen-anhalt_dessau-roßlau" = "dessau-roßlau",
               "germany_sachsen-anhalt_halle (saale)" = "halle (saale)",
               "germany_sachsen-anhalt_harz" = "harz",
               "germany_sachsen-anhalt_jerichower land" = "jerichower land",
               "germany_sachsen-anhalt_magdeburg" = "magdeburg",
               "germany_sachsen-anhalt_mansfeld-südharz" = "mansfeld-südharz",
               "germany_sachsen-anhalt_saalekreis" = "saalekreis",
               "germany_sachsen-anhalt_salzlandkreis" = "salzlandkreis",
               "germany_sachsen-anhalt_stendal" = "stendal",
               "germany_sachsen-anhalt_wittenberg" = "wittenberg",
               "germany_schleswig-holstein_dithmarschen" = "dithmarschen",
               "germany_schleswig-holstein_flensburg" = "flensburg",
               "germany_schleswig-holstein_herzogtum lauenburg" = "herzogtum lauenburg",
               "germany_schleswig-holstein_kiel" = "kiel",
               "germany_schleswig-holstein_lübeck" = "lübeck",
               "germany_schleswig-holstein_neumünster" = "neumünster",
               "germany_schleswig-holstein_nordfriesland" = "nordfriesland",
               "germany_schleswig-holstein_ostholstein" = "ostholstein",
               "germany_schleswig-holstein_pinneberg" = "pinneberg",
               "germany_schleswig-holstein_plön" = "plön",
               "germany_schleswig-holstein_rendsburg-eckernförde" = "rendsburg-eckernförde",
               "germany_schleswig-holstein_schleswig-flensburg" = "schleswig-flensburg",
               "germany_schleswig-holstein_segeberg" = "segeberg",
               "germany_schleswig-holstein_steinburg" = "steinburg",
               "germany_schleswig-holstein_stormarn" = "stormarn",
               "germany_thüringen_altenburger land" = "altenburger land",
               "germany_thüringen_eichsfeld" = "eichsfeld",
               "germany_thüringen_eisenach" = "eisenach",
               "germany_thüringen_erfurt" = "erfurt",
               "germany_thüringen_gera" = "gera",
               "germany_thüringen_gotha" = "gotha",
               "germany_thüringen_greiz" = "greiz",
               "germany_thüringen_hildburghausen" = "hildburghausen",
               "germany_thüringen_ilm-kreis" = "ilm-kreis",
               "germany_thüringen_jena" = "jena",
               "germany_thüringen_kyffhäuserkreis" = "kyffhäuserkreis",
               "germany_thüringen_nordhausen" = "nordhausen",
               "germany_thüringen_saale-holzland-kreis" = "saale-holzland-kreis",
               "germany_thüringen_saale-orla-kreis" = "saale-orla-kreis",
               "germany_thüringen_saalfeld-rudolstadt" = "saalfeld-rudolstadt",
               "germany_thüringen_schmalkalden-meiningen" = "schmalkalden-meiningen",
               "germany_thüringen_sömmerda" = "sömmerda",
               "germany_thüringen_sonneberg" = "sonneberg",
               "germany_thüringen_suhl" = "suhl",
               "germany_thüringen_unstrut-hainich-kreis" = "unstrut-hainich-kreis",
               "germany_thüringen_wartburgkreis" = "wartburgkreis",
               "germany_thüringen_weimar" = "weimar",
               "germany_thüringen_weimarer land" = "weimarer land",
               "germany_baden-württemberg" = "baden-württemberg$",
               "germany_bayern" = "bayern$",
               "germany_berlin" = "berlin$",
               "germany_brandenburg" = "brandenburg$",
               "germany_bremen" = "bremen$",
               "germany_hamburg" = "hamburg$",
               "germany_hessen" = "hessen$",
               "germany_mecklenburg-vorpommern" = "mecklenburg-vorpommern$",
               "germany_niedersachsen" = "niedersachsen$",
               "germany_nordrhein-westfalen" = "nordrhein-westfale$",
               "germany_rheinland-pfalz" = "rheinland-pfalz$",
               "germany_saarland" = "saarland$",
               "germany_sachsen" = "sachsen$",
               "germany_sachsen-anhalt" = "sachsen-anhalt$",
               "germany_schleswig-holstein" = "schleswig-holstein$",
               "germany_thüringen" = "thüringen$",
               "germany" = "^germany$")
  
  for (i in 1:length(germany)){
    if(any(grepl(germany[[i]], x))){
      x <- names(germany)[[i]]
    }
  }
  
  return(x)
}  
  # Make tipnames
  
write_lines(paste0('"', Netherlands$match, '" = "', str_split(Netherlands$match, pattern = '_') %>% lapply(., tail, 1) %>% unlist(), '",'), 'test.txt')


germany = geodata %>% filter(country == 'germany')
write_lines(paste0('"', germany$match, '" = "', str_split(germany$match, pattern = '_') %>% lapply(., tail, 1) %>% unlist(), '",'), 'test.txt')